### ISSUE TITLE
Instalasi failed

### ISSUE THREAD

**Issue by horasjey** [willnode/ci4-admin-lte#1]
salah nya di mana yach kak..?
![image](https://github.com/willnode/ci4-admin-lte/assets/45363813/408395f2-0170-45d7-ac51-58a4c5e456cb)

**Comment by willnode** [comment]
Ini perlu update versi CI nya kak

**Comment by willnode** [comment]
[Sudah di update](https://github.com/willnode/ci4-admin-lte/commit/6b395174a2fc6bdbfcca05ef6e013021d9643345) ya 👍

**Comment by horasjey** [comment]
> [Sudah di update](https://github.com/willnode/ci4-admin-lte/commit/6b395174a2fc6bdbfcca05ef6e013021d9643345) ya +1

Baik kak,
terima kasih , saya coba install ulang lagi kak

**Comment by horasjey** [comment]
> [Sudah di update](https://github.com/willnode/ci4-admin-lte/commit/6b395174a2fc6bdbfcca05ef6e013021d9643345) ya +1

saya sudah install untuk homepage dan login berfungsi dengan baik kak,
untuk fitur register eror kak,
kira-kira salahnya di mana yach kak..?
![image](https://github.com/willnode/ci4-admin-lte/assets/45363813/f350722a-198f-4a98-9100-f3d6301aea96)

**Comment by horasjey** [comment]
> > [Sudah di update](https://github.com/willnode/ci4-admin-lte/commit/6b395174a2fc6bdbfcca05ef6e013021d9643345) ya +1
> 
> saya sudah install untuk homepage dan login berfungsi dengan baik kak, untuk fitur register eror kak, kira-kira salahnya di mana yach kak..? ![image](https://user-images.githubusercontent.com/45363813/252571231-f350722a-198f-4a98-9100-f3d6301aea96.png)

![image](https://github.com/willnode/ci4-admin-lte/assets/45363813/fc1f19f3-12b7-4d53-83a3-7da8667ebce9)

**Comment by willnode** [comment]
> untuk fitur register eror kak, kira-kira salahnya di mana yach kak..?

[Typo](https://github.com/willnode/ci4-admin-lte/commit/279042516e88eeaff3bb2279c47856510cb1601d)

**Comment by willnode** [comment]
closed as solved.
